Update all local changes to master branch.

diff --git a/dcm/dcm_delete b/dcm/dcm_delete
--- a/dcm/dcm_delete
+++ b/dcm/dcm_delete
@@ -6,14 +6,11 @@ STS_PATH="/home/unmesh/iox_test/dcm/sts"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${STS_PATH}
 }
 
 parse_logger()
@@ -21,22 +18,23 @@ parse_logger()
 	sleep 5
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
-		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
-}
-
-parse_sts()
-{
-	sleep 5
-	if [[ -s ${STS_PATH} ]];
-	then 
-		out=$(grep 'mru' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B11 -A1 "regex" ${STS_PATH})
-		sleep 2
-		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
-		echo "state : "${state}
-	fi
+	rm ${LOGGER_PATH}
 }
 
 dcm_delete_test1()
@@ -67,3 +65,4 @@ dcm_delete_test2
 dcm_delete_test3
 
 kill_process
+
diff --git a/dio/do/do_deep b/dio/do/do_deep
--- a/dio/do/do_deep
+++ b/dio/do/do_deep
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/dio/do/logger"
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
-    rm ${LOGGER_PATH}
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 parse_logger()
@@ -19,28 +16,42 @@ parse_logger()
 	sleep 5
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
-		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
+}
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
 }
 
 do_deep_test1()
 {
-
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/dqo/1/do-val/value"
+	subscribe_logger_event &
+	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/dqo/1/do-val/value"
 	parse_logger
 
 }
 
 do_deep_test2()
 {
-
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/do/1/do-val123/value"
+	subscribe_logger_event &
+	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1/do-val123/value"
 	parse_logger
 
 }
@@ -48,33 +59,27 @@ do_deep_test2()
 
 do_deep_test3()
 {
-
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/do/1" &
-	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/do/1"
+	subscribe_logger_event &
+#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
+	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 
 }
 
 do_deep_test4()
 {
-
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/do/1" &
-	mosquitto_pub -m '{"value":{"type":"frequency","level":false,"frequency":1,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/do/1/do-val"
+	subscribe_logger_event &
+#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
+	mosquitto_pub -m '{"value":{"type":"frequency","level":false,"frequency":1,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1/do-val"
 	parse_logger
 
 }
 
 do_deep_test5()
 {	
-
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/do/1" &
-	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/do/1/do-val/value"
+	subscribe_logger_event &
+#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
+	mosquitto_pub -m '{"frequency":10}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1/do-val/value"
 	parse_logger
 }
 
@@ -87,3 +92,4 @@ do_deep_test4
 do_deep_test5
 
 kill_process
+
diff --git a/dio/do/do_get b/dio/do/do_get
--- a/dio/do/do_get
+++ b/dio/do/do_get
@@ -2,13 +2,11 @@
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 do_get_test1()
@@ -68,3 +66,4 @@ do_get_test6
 
 sleep 10
 kill_process
+
diff --git a/dio/do/do_mode b/dio/do/do_mode
--- a/dio/do/do_mode
+++ b/dio/do/do_mode
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/dio/do/logger"
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
-    rm ${LOGGER_PATH}
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 parse_logger()
@@ -19,17 +16,34 @@ parse_logger()
 	sleep 5
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
-		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
+
 
 do_mode_test1()
 {
-
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 
@@ -37,9 +51,7 @@ do_mode_test1()
 
 do_mode_test2()
 {
-
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/2" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":false,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -48,9 +60,7 @@ do_mode_test2()
 
 do_mode_test3()
 {
-
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":"true","frequency":0,"pulse":0,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 
@@ -58,9 +68,7 @@ do_mode_test3()
 
 do_mode_test4()
 {
-
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pulse","level":false,"frequency":0,"pulse":1000,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -69,9 +77,7 @@ do_mode_test4()
 
 do_mode_test5()
 {
-
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pulse","level":false,"frequency":0,"pulse":60000,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -80,9 +86,7 @@ do_mode_test5()
 
 do_mode_test6()
 {
-
-	echo "test6 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pulse","level":true,"frequency":0,"pulse":"test","pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 
@@ -90,9 +94,7 @@ do_mode_test6()
 
 do_mode_test7()
 {
-
-	echo "test7 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":1,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -101,9 +103,7 @@ do_mode_test7()
 
 do_mode_test8()
 {
-
-	echo "test8 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":20000,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -112,9 +112,7 @@ do_mode_test8()
 
 do_mode_test9()
 {
-
-	echo "test9 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":true,"frequency":"test","pulse":0,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 
@@ -122,9 +120,7 @@ do_mode_test9()
 
 do_mode_test10()
 {
-
-	echo "test10 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pwm","level":false,"frequency":0,"pulse":0,"pwm":{"frequency":1,"duty-cycle":10}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -133,9 +129,7 @@ do_mode_test10()
 
 do_mode_test11()
 {
-
-	echo "test11 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pwm","level":false,"frequency":0,"pulse":0,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -144,18 +138,14 @@ do_mode_test11()
 
 do_mode_test12()
 {
-
-	echo "test12 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pwm","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":"test","duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 }
 
 do_mode_test13()
 {
-
-	echo "test13 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"pwm","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":"test","duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
 }
@@ -175,3 +165,4 @@ do_mode_test12
 do_mode_test13
 
 kill_process
+
diff --git a/dio/do/do_port b/dio/do/do_port
--- a/dio/do/do_port
+++ b/dio/do/do_port
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/dio/do/logger"
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
-	rm ${LOGGER_PATH}
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 parse_logger()
@@ -19,17 +16,34 @@ parse_logger()
 	sleep 5
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
-		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
+
 
 do_port_test1()
 {
-
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
 	parse_logger
@@ -37,9 +51,7 @@ do_port_test1()
 
 do_port_test2()
 {
-
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/2" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/2"
 	parse_logger
@@ -47,9 +59,7 @@ do_port_test2()
 
 do_port_test3()
 {
-
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/3" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/3"
 	parse_logger
@@ -57,9 +67,7 @@ do_port_test3()
 
 do_port_test4()
 {
-
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/4" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/4"
 	parse_logger
@@ -67,9 +75,7 @@ do_port_test4()
 
 do_port_test5()
 {
-
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/5" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/5"
 	parse_logger
@@ -77,9 +83,7 @@ do_port_test5()
 
 do_port_test6()
 {
-
-	echo "test6 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/6" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/6"
 	parse_logger
@@ -87,9 +91,7 @@ do_port_test6()
 
 do_port_test7()
 {
-
-	echo "test7 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 #	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/8" &
 	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/8"
 	parse_logger
@@ -104,3 +106,4 @@ do_port_test6
 do_port_test7
 
 kill_process
+
diff --git a/dio/relay/relay_dvc b/dio/relay/relay_dvc
--- a/dio/relay/relay_dvc
+++ b/dio/relay/relay_dvc
@@ -2,99 +2,97 @@
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 relay_dvc_test1()
 {
 	mosquitto_sub -t "glp/0/./=control/service" &
 	mosquitto_sub -t "glp/0/./=engine/dvc/dio/relay/1/respond" &
-	mosquitto_pub -m '{"value":{"level":true}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_pub -m '{"value":{"level":true}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 
 }
 
 relay_dvc_test2()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":16,"value":{"level":false}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":16,"value":{"level":false}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 
 }
 
 relay_dvc_test3()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":15,"active":true,"value":{"level":true}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":15,"active":true,"value":{"level":true}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 
 }
 
 relay_dvc_test4()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":14,"active":false,"value":{"level":false}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":14,"active":false,"value":{"level":false}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 
 }
 
 relay_dvc_test5()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"value":{"level":false}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"value":{"level":false}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 relay_dvc_test6()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":15,"value":{"level":false}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":15,"value":{"level":false}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 
 }
 
 relay_dvc_test7()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":14,"value":{"level":true}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":14,"value":{"level":true}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 relay_dvc_test8()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":15,"active":false}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":15,"active":false}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 relay_dvc_test9()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":14,"active":true,"value":{"level":true}}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":14,"active":true,"value":{"level":true}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 relay_dvc_test10()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":17,"value":null}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":17,"value":null}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 relay_dvc_test11()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":16,"value":null}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":16,"value":null}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 
 relay_dvc_test12()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":14,"value":null}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":14,"value":null}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 
 relay_dvc_test13()
 {
-	mosquitto_sub -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val" &
-	mosquitto_pub -m '{"prio":15,"value":null}' -t "glp/0/T6tWyga/rq/dev/iox/dio/if/relay/1/relay-val"
+	mosquitto_sub -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val" &
+	mosquitto_pub -m '{"prio":15,"value":null}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1/relay-val"
 }
 
 
@@ -119,3 +117,4 @@ relay_dvc_test13
 
 sleep 10
 kill_process
+
diff --git a/dio/relay/relay_get b/dio/relay/relay_get
--- a/dio/relay/relay_get
+++ b/dio/relay/relay_get
@@ -2,13 +2,11 @@
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 relay_get_test1()
@@ -20,7 +18,7 @@ relay_get_test1()
 relay_get_test2()
 {
 	mosquitto_sub -t "my/responses" &
-	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox1234/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
+	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
 }
 
 relay_get_test3()
@@ -57,3 +55,4 @@ relay_get_test6
 
 sleep 10
 kill_process
+
diff --git a/dio/relay/relay_valueObj b/dio/relay/relay_valueObj
--- a/dio/relay/relay_valueObj
+++ b/dio/relay/relay_valueObj
@@ -2,13 +2,11 @@
 
 kill_process()
 {
-    pkill mosquitto_sub
-    if [[ $? -eq 0 ]];
-    then
-        echo "mosquitto_sub process killed"
-    else
-        echo "failed to kill mosquitto_sub process"
-    fi
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
+	then
+		echo "failed to kill mosquitto_sub process"
+	fi
 }
 
 
@@ -24,3 +22,4 @@ relay_valueObj_test1
 sleep 10
 
 kill_process
+
diff --git a/meter/3phase/3phase_create b/meter/3phase/3phase_create
--- a/meter/3phase/3phase_create
+++ b/meter/3phase/3phase_create
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
 }
 
 parse_logger()
@@ -20,89 +17,96 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
+}
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
 }
 
 
-	
 3phase_create_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test2()
 {
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test3()
 {
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test4()
 {
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test5()
 {
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test6()
 {
-	echo "test6 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true}}' -t "glp/0/17q2d9v/rq/dev/iox/amik_1/do"
 	parse_logger
 }
 
 3phase_create_test7()
 {
-	echo "test7 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true,"unid":"abcd"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test8()
 {
-	echo "test8 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":"true","unid":"257"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test9()
 {
-	echo "test9 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":false}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_create_test10()
 {
-	echo "test10 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":true}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
@@ -119,3 +123,4 @@ parse_logger()
 3phase_create_test10
 
 kill_process
+
diff --git a/meter/3phase/3phase_deep b/meter/3phase/3phase_deep
--- a/meter/3phase/3phase_deep
+++ b/meter/3phase/3phase_deep
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
 }
 
 parse_logger()
@@ -20,32 +17,46 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
 
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
 
 3phase_deep_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/dia/1/di-val/monitor/rate"
 	parse_logger
 }
 
 3phase_deep_test2()
 {
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1/di-vala/monitor/rate"
 	parse_logger
 }
 
 3phase_deep_test3()
 {
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
 	mosquitto_pub -m '{"monitor":{"rate":100}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS"
 	parse_logger
@@ -53,8 +64,7 @@ parse_logger()
 
 3phase_deep_test4()
 {
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
 	mosquitto_pub -m '{"rate":100}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS/monitor"
 	parse_logger
@@ -62,8 +72,7 @@ parse_logger()
 
 3phase_deep_test5()
 {
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
 	mosquitto_pub -m '20' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS/monitor/rate"
 	parse_logger
@@ -76,3 +85,4 @@ parse_logger()
 3phase_deep_test5
 
 kill_process
+
diff --git a/meter/3phase/3phase_repair b/meter/3phase/3phase_repair
--- a/meter/3phase/3phase_repair
+++ b/meter/3phase/3phase_repair
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
 }
 
 parse_logger()
@@ -20,20 +17,37 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
 
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
 
 3phase_repair_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
-	mosquitto_pub -m '{"action":"repair"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
+	subscribe_logger_event &
+	mosquitto_pub -m '{"action":"repair"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
 	parse_logger
 }
 
 3phase_repair_test1
 
 kill_process
+
diff --git a/modbus/modbus_create b/modbus/modbus_create
--- a/modbus/modbus_create
+++ b/modbus/modbus_create
@@ -5,15 +5,11 @@ STS_PATH="/home/unmesh/iox_test/modbus/sts"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
-	rm ${STS_PATH}
 }
 
 parse_logger()
@@ -22,27 +18,56 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
 
 parse_sts()
 {
+	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
 	sleep 5
 	if [[ -s ${STS_PATH} ]];
 	then 
 		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
 		sleep 2
 		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
-		echo "state : "${state}
+		if [[ ${state} == "unprovisioned" ]];
+		then
+			STS_RESULT="PASS"
+		else
+			STS_RESULT="FAIL"
+		fi
 	fi
+	rm ${STS_PATH}
+}
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
+
+subscribe_sts_event()
+{
+	 mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} 
 }
 
 modbus_create_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
@@ -51,39 +76,35 @@ modbus_create_test1()
 modbus_create_test3()
 {
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
+	subscribe_sts_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_sts
 }
 
 modbus_create_test4()
 {
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
 
 modbus_create_test5()
 {
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900000000000DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
 
 modbus_create_test6()
 {
-	echo "test6 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/new_device.0/do"
 	parse_logger
 }
 
 modbus_create_test7()
 {
-	echo "test7 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
@@ -91,15 +112,14 @@ modbus_create_test7()
 modbus_create_test8()
 {
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
+	subscribe_sts_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"false","unid":"01:43"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_sts
 }
 
 modbus_create_test9()
 {
-	echo "test9 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true","unid":"abcd"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
@@ -107,10 +127,11 @@ modbus_create_test9()
 modbus_create_test10()
 {
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
+	subscribe_sts_event &
+	parse_sts
 	mosquitto_sub -t "glp/0/17q2d9v/fb/res/type/blk.900014150040DB00/0" &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/0" &
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
+	subscribe_sts_event &
 	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true","unid":"01:1"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_sts
 }
@@ -127,3 +148,4 @@ modbus_create_test9
 modbus_create_test10
 
 kill_process
+
diff --git a/modbus/modbus_deep b/modbus/modbus_deep
--- a/modbus/modbus_deep
+++ b/modbus/modbus_deep
@@ -4,14 +4,11 @@ LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
 }
 
 parse_logger()
@@ -20,44 +17,46 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
 
-parse_sts()
+subscribe_logger_event()
 {
-	sleep 5
-	if [[ -s ${STS_PATH} ]];
-	then 
-		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
-		sleep 2
-		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
-		echo "state : "${state}
-	fi
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
 }
-
 
 modbus_deep_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/7"
 	parse_logger
 }
 
 modbus_deep_test2()
 {
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"dummy":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/1"
 	parse_logger
 }
 	
 modbus_deep_test3()
 {
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
 	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1"
 	parse_logger
@@ -65,8 +64,7 @@ modbus_deep_test3()
 
 modbus_deep_test4()
 {
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
 	mosquitto_pub -m '{"monitor":{"rate":20}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B"
 	parse_logger
@@ -74,8 +72,7 @@ modbus_deep_test4()
 
 modbus_deep_test5()
 {
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
 	mosquitto_pub -m '{"rate":30}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor" 
 	parse_logger
@@ -83,8 +80,7 @@ modbus_deep_test5()
 
 modbus_deep_test6()
 {
-	echo "test6 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
 	mosquitto_pub -m '40' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor/rate"
 	parse_logger
@@ -98,3 +94,4 @@ modbus_deep_test5
 modbus_deep_test6
 
 kill_process
+
diff --git a/modbus/modbus_delete b/modbus/modbus_delete
--- a/modbus/modbus_delete
+++ b/modbus/modbus_delete
@@ -5,15 +5,11 @@ STS_PATH="/home/unmesh/iox_test/modbus/sts"
 
 kill_process()
 {
-	pkill mosquitto_sub
-	if [[ $? -eq 0 ]];
+	pkill mosquitto_sub 
+	if [[ $? -eq 1 ]];
 	then
-		echo "mosquitto_sub process killed"
-	else
 		echo "failed to kill mosquitto_sub process"
 	fi
-	rm ${LOGGER_PATH}
-	rm ${STS_PATH}
 }
 
 parse_logger()
@@ -22,36 +18,64 @@ parse_logger()
 	if [[ -s ${LOGGER_PATH} ]];
 	then 
 		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
-		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
-		echo "parse : "${parse}
+		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
+		if [[ ${last_out_time} == ${out_time} ]];
+		then
+			echo "NO NEW MESSAGE FROM LOGGER"
+		else
+			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
+			if [[ ${parse} == ${1} ]];
+			then
+				LOGGER_RESULT="PASS"
+			else
+				LOGGER_RESULT="FAIL"
+			fi
+			last_out_time=${out_time}
+		fi
 	fi
+	rm ${LOGGER_PATH}
 }
 
 parse_sts()
 {
+	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
 	sleep 5
 	if [[ -s ${STS_PATH} ]];
 	then 
 		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
 		sleep 2
 		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
-		echo "state : "${state}
+		if [[ ${state} == "unprovisioned" ]];
+		then
+			STS_RESULT="PASS"
+		else
+			STS_RESULT="FAIL"
+		fi
 	fi
+	rm ${STS_PATH}
+}
+
+subscribe_logger_event()
+{
+    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
+}
+
+subscribe_sts_event()
+{
+	 mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} 
 }
 
 modbus_delete_test1()
 {
-	echo "test1 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
 
 modbus_delete_test2()
 {
-	echo "test2 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
+	subscribe_sts_event &
 	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 	parse_sts
@@ -59,17 +83,15 @@ modbus_delete_test2()
 
 modbus_delete_test3()
 {
-	echo "test3 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
 
 modbus_delete_test4()
 {
-	echo "test4 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
+	subscribe_sts_event &
 	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 	parse_sts
@@ -77,8 +99,7 @@ modbus_delete_test4()
 
 modbus_delete_test5()
 {
-	echo "test5 : " > ${LOGGER_PATH}
-	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
+	subscribe_logger_event &
 	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
 	parse_logger
 }
@@ -90,3 +111,4 @@ modbus_delete_test4
 modbus_delete_test5
 
 kill_process
+
